export const ITEM_DROPS = [
    { name: "Debug Elixir",      emoji: "🧪", type: "heal",    amount: 6,         min_tier: 1,
      flavor: "Traces the error. Restores the damage." },
    { name: "Restore Point",     emoji: "💾", type: "heal",    amount: 10,        min_tier: 4,
      flavor: "Roll back to a healthier state." },
    { name: "Hot Patch Vial",    emoji: "💊", type: "heal",    amount: 7,         min_tier: 2,
      flavor: "Applied at runtime. No restart needed." },
    { name: "Recovery Packet",   emoji: "📡", type: "heal",    amount: 8,         min_tier: 3,
      flavor: "Delivered with guaranteed reliability." },
    { name: "Overclock Rune",    emoji: "⚡", type: "attack",  attack_mult: 2.0,  min_tier: 6,
      flavor: "Pushes your attack beyond rated spec." },
    { name: "Brute Force Sigil", emoji: "⚔", type: "attack",  attack_mult: 1.5,  min_tier: 3,
      flavor: "Try every possibility until one hits." },
    { name: "Pipeline Booster",  emoji: "⚙", type: "attack",  attack_mult: 1.75, min_tier: 4,
      flavor: "No stalls. Maximum throughput." },
    { name: "Parallel Strike",   emoji: "↯", type: "attack",  attack_mult: 2.5,  min_tier: 8,
      flavor: "Two threads. One target." },
    { name: "Firewall Shard",    emoji: "🛡", type: "defense", defense_reduce: 0.5, min_tier: 3,
      flavor: "Blocks unauthorized incoming damage." },
    { name: "Encryption Ward",   emoji: "🔒", type: "defense", defense_reduce: 0.6, min_tier: 6,
      flavor: "Damage denied — wrong key." },
    { name: "Redundancy Charm",  emoji: "🔄", type: "defense", defense_reduce: 0.4, min_tier: 2,
      flavor: "If the first defense fails, the second holds." },
    { name: "Sandboxed Amulet",  emoji: "🔐", type: "defense", defense_reduce: 0.5, min_tier: 4,
      flavor: "Damage contained. System isolated." },
];